### ISSUE TITLE
Implement the agreement field formatter

### ISSUE THREAD

**Issue by capynet** [capynet/DrupalPayPalRecurrringPayment#19]
Must print:
- Agreement name
- Payment cycle date.
- Amount
- Cancel button.

**Comment by fran** [comment]
@capynet I have pushed the field formatter with the basic information, with that info you can start with the theming. 
I still need to improve the data (i.e remaining cycles) and work in how cache the data.

**Comment by capynet** [comment]
Done!

![image](https://user-images.githubusercontent.com/1402913/36077094-90f8f058-0f66-11e8-91ee-8c0665e79279.png)
